config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
	get 'signup' =>'users#new'
	resources :users
	get 'login' => 'sessions#new'
	post 'login' =>'sessions#create'
	delete 'logout' =>'sessions#destroy'
	root 'users#index' 
get 'about'=>'users#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	has_one_attached :image

	before_save {self.email = email.downcase }
	validates :name,presence: true,length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+\.[a-z]+\z/i
	validates :email,presence: true,length: { maximum: 255 },
	format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password,length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception
include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :check_for_logout, only: [:new] 


 def new
  end


def create
user = User.find_by(email: params[:session][:email].downcase)
if user && user.authenticate(params[:session][:password])
log_in user
redirect_to user
else
flash.now[:danger] = 'Invalid email/password combination'
render 'new'
def correct_user
@user = User.find(params[:id])
# redirect_to(root_url) unless current_user?(@user)
redirect_to(root_url) unless @user == current_user
end
end
end

def destroy
log_out
redirect_to root_url
end


	def check_for_logout
				unless logged_out?
					flash[:danger]="please log out first"
					redirect_to	user_path(current_user) 
				end
		end
				

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :logged_in_user,only: [:edit,:update]
before_action :correct_user,only: [:edit,:update]  
before_action :check_for_logout, only: [:new]


	def new
		@user = User.new
  end

	def show
		@user = User.find(params[:id])
	end
	
	def index
		@users=User.all
	end


def create
@user = User.new(user_params)
if @user.save
log_in @user
flash[:success] = "User successfully logged in!"
redirect_to @user
else
render 'new'
end
end

def edit
@user = User.find(params[:id])
end



def update
@user = User.find(params[:id])
if @user.update_attributes(user_params)
flash[:success] = "Profile updated"
redirect_to @user
else
render 'edit'
end
end



	def check_for_logout
				unless logged_out?
					flash[:danger]="please log out first"
					redirect_to	user_path(current_user)
				end
		end

private
def user_params
params.require(:user).permit(:name,:email,:password,
:password_confirmation,:image)
end

def logged_in_user
unless logged_in?
flash[:danger] = "Please log in."
redirect_to login_url
end


def correct_user
@user = User.find(params[:id])
# redirect_to(root_url) unless current_user?(@user)
redirect_to(root_url) unless @user == current_user
end

def about
		@users = User.all
end

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


def log_in(user)
session[:user_id] = user.id
end

def current_user
@current_user ||= User.find_by(id: session[:user_id])
end

def logged_in?
!current_user.nil?
end

def log_out
session.delete(:user_id)
@current_user = nil
end

def logged_out?
		current_user.nil?		
end




end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Userauth20</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


	<% flash.each do |message_type,message| %>
		<div class="alert alert-<%= message_type %>">
			<%= message %>
		</div>
	<% end %>

	<header class="navbar navbar-expand-sm bg-light ">
		<div class="container">	
 			<%= link_to "Home", users_path %>
			<ul class="nav navbar-nav navbar-right">	
					<li class="nav-link"><%=link_to "something", "#"%></li>
					<li class="nav-link"><%=link_to "about", about_path%></li>
					<% if logged_in? %>
 						<div class="dropdown">
						  <li class="nav-link dropdown-toggle" data-toggle="dropdown">
					  	<%=link_to @user.name%>  </li>
						  <div class="dropdown-menu">
								<li class="nav-link"><%= link_to "Log out", logout_path, method:"delete" %></li>
								<li class="nav-link"><%=link_to "edit", edit_user_path(@user.id)%></li>
						 	 </div>
						</div> 
					<% else %>						
					<li class="nav-link"><%=link_to "Log in", login_path%></li>
					<% end %>
			</ul>
		</div>
	</header>	




    <%= yield %>

  </body>
</html>

app/views/users/about.html.erb
<h1>About Us</h1>
<h5>Hey there, I am Imran Shah. This is our bonus marks task. This project has strong validations.<br> we are supposed to make a full flegged rails <br>project and upload it to VPS. our team members in this task are following: <br><br>
Leader: <strong>Imran Shah</strong><br> 
Roll no 07<br><br>
member: Muhammad Saleem<br> 
Roll no 18<br><br>
member: Manzoor Ahmed<br>
Roll no 30<br>
<br>
member: Shabahat<br>
Roll no 34<br><br>
</h5>

app/views/users/edit.html.erb
<h1>Update your profile</h1>
<%= form_for(@user) do |f| %>


<% if @user.errors.any? %>
				<div id="error_explanation">
					<div class="alert alert-danger">
						The form contains
						<%= pluralize(@user.errors.count,"error") %>
					</div>
						<ul>
						<% @user.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>



<%= f.label :name %>
<%= f.text_field :name,class: 'form-control' %>
<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>
<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>
<%= f.label :password_confirmation,"Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

				<div class="field">
					<%= f.label :image %>
					<%= f.file_field :image %>
				</div>
<%= f.submit "Save changes",class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<h1>listing all users</h1>
<table>
	<tr>	
		<th><h3>Name:  </h3></th>
		<th><bold><h3>email:  </h3></bold></th>
	</tr>
	<% @users.each do |user|%>
		<tr>	
			<td><strong><%= user.name %></strong>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</td>
			<td><strong><%= user.email %></strong>&emsp;</td>
	
<td><%= link_to image_tag(user.image, style:'width:90px',height:'90px'), user_path(user)%></td>
		</tr>
	<%end%>
</table>
<p> New user? <%= link_to "Sign up now!",signup_path %></p>

app/views/users/new.html.erb
<h1> Sign up </h1>
<div class="row">
	<div class="col-md-6 offset-md-3">
		<%= form_for(@user) do |f| %>
			<% if @user.errors.any? %>
				<div id="error_explanation">
					<div class="alert alert-danger">
						The form contains
						<%= pluralize(@user.errors.count,"error") %>
					</div>
						<ul>
						<% @user.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control'%>
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>
			<%= f.label :password_confirmation,"Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>
				<div class="field">
					<%= f.label :image %>
					<%= f.file_field :image %>
				</div>
			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h6>Pic</h6>
<%= image_tag(@user.image, style:'width:90px')%><br>
<%= @user.name %> <br>
<%= @user.email %>